openapi: 3.0.0
info:
  title: daysAPI
  version: 1.0.0
servers:
  - url: https://determined-erin-pelican.cyclic.app/api/v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /auth/register:
    post:
      tags:
        - auth
      summary: auth register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Zian
                email: zian@zianxie.com
                password: asdfasdf
      security: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - auth
      summary: auth login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: zian@zianxie.com
                password: asdfasdf
      security: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /days:
    post:
      tags:
        - crud
      summary: create a day
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                date: '2023-02-08'
                description: some day special
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - crud
      summary: get all days
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /days/{id}:
    parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Numeric ID of the user to get
    get:
      tags:
        - crud
      summary: get one day
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - crud
      summary: update a day
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                date: '2023-03-08'
                description: a delayed special day
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - crud
      summary: delete a day
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}